version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: e-commerce-mysql-container-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gabify_Solutions123
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Talaoc.12535
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
